name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/depasinfection-fe-25
            git reset --hard origin/main  
            git clean -fd  
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            rm -rf .next  
            pnpm run build
            pm2 restart depasinfection-fe-25

      - name: Notify Success
        if: success()
        run: echo "🚀 Deployment was successful"
